addons:
  postgresql: 9.6
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
language: ruby
rvm:
- 2.5.3
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
env:
  global:
    AWS_ACCESS_KEY:
      - secure: "RDRRFF33O7mYFEdynuCaoCoVMQ8a2lHWEoFUC7XGuKqAW5coKdkhAfKz2pgW9ei4klMmB4ul5zTxe2biXJx5eRZYPubyfpGGvsaGtijLq+Lg5NGEzLxXHHJHmx1I535WBVBD9YC6YCzEdq5YGOf/e6h2MLe0W06kSz9bwmmZ+XQqR2Giysj8DGD1FzG5NNb76DBqRCr3FQgOOivXpDYTPIDJrsSGOV0NysJRlvYJbGKACJkAdwXDGEGjG4UoVIXDm0bic8GEwJV7+CNdScX4jv22+w09bBHo6qMUI1dDbVhKP68ttxTp2fpr30FnHpLG7a9nz8dHMPeO42rqheXIbU6twM+HkE9ckrmhsmccWZY5KXM4BW17IDUl3aXYm0bLVVFMgXPYSLfblbW4N/hc+WvYoKpog3WtxDA/VtCAV0q/GCoyyJl1RZ4tksSdSlGau4O5mtUPUXbfxt5lm1Lihw70xmX6CIaYTPOejkoVDjaxU7s/hstdbZyfj/f3CRLfuIcBh2LWyM1F9UBGe2w8E7TkC2Brzluv97E/kuCHa1n6acYRLv3KzFW7luyLHN0J13lvL9rw8A/Qgqe0nuna5yK8CHxHYBU22v0VK1+oshNr3MVbC2D3a8/TE1aIOl71gpySTXwU2SPjclP93Q7LXUbwpOCWnvmLN8Rucr8MhVY="
    AWS_SECRET_KEY:
      - secure: "SmvAzimY8fcxXUfcGOHCm36R2Tk4/GwtVW4Ra8HtAF+GTPcWVEkUlIQzE6RK/We0U4G5tqrNujFhUDkYJHylcEhAExLozfex0nDoIN7uEmtrTMM5CSnTYLbc5RL47cBhAIcBLOagx2c08VTDpn6HGWTWiJ5pjUx4S6O0kih4D2hVJ0xa8FuweGbF7yVh6y16ZIEhWogbddx2g5Agz8SKsCDUIASf0RZpFqjm4TeTDaco+qqFzO3tBLZtPjqQukZqsZ0Kt4iy5R4rDyV4mh1o+WdBSGEqVtUc6vc51qV/RAamAIZg3UKjhIG/7ncE2UR6442RwX9Y3effYQ5xOSPBqT8w4thy+KvEdlvOU0qG6OGRkycJNlDWtj2J3OTyS3VEWhZx5HgjYTOHSArBUz7y1E8idaDX4svm8Id1xuawMCtzk1c+vZDKKbtziq/avo5UQtKi+iZUJQAsHHrXX0p7ERCEHEOh99BmKkQwAh/w2jZoHTT87xyVedM5E8uWOwWfJwe0AiJxWHLCf9xyDJ9s5rDMz65fuB/b5StghZI3hJsiioZqKfSCgR4csMuQY2cUunjdZBKKVUXTFLRB74gqGyWiOFlFRh1l9+0UH8r91On1aiXZyW77aLjDXzXS/8Z9BdfonRNFR+vDehD3DjeCb1iEdZ0Rd8IN9E86PJ8h4GI="
    AWS_BUCKET: 
      - "grams-joel-pankito"