addons:
  postgresql: 9.6
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
language: ruby
rvm:
- 2.5.3
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
env:
  global:
  - secure: NRx8pJJrzFwYTSPI0tcl/DUafcrGV47TWTG71/jIJR//h70OYi7CdLxV0nYrm8B2RnFmxPaFa+oM7xKPF7q2oR8Ct3S8aDhiJTxD2pASEynqZHR1Mv29A8cknHpgLmX4M22rI9qudSH85p3jESVsegjsJ77Ve+E3dyxjywBxKHIi6+gJD0nKm8IRFxmuL3sU5DK4/Olmc33R3JddMPIu2gpKbT81nYZst0LGVISVMkGoN1T9D9xo7PH60J1dZq4HfPYQHWVGFk0s+gBT4yhoi5dic5z+GbGLa52wL6XpowHfxUZFT/N2Wx74+wD8dDtFopotlcIoOD8zz3Zl5HsD7nRcRy2X6y3KIqI2U4/ajDVVaA1xLzJF6SJ+q2lFyf/iR9gOzZjRbY5zgaaX8xwJf8Cwn3nC2CRdYHO7Fgdjj8LGPFRtP4LSFv8YDi/1HP7Rg0/39b2acgzOPIG3HktD79Ca4GKeZ/sWGquT+XNa5JUr+xCu8nhO/9fhvU6ZI4gvY9iAutuNf8PSYHWu7BohKWPZAIz/CjMkxgbPNKqkZMvpfRFRm45DwSQmkD4Gh8Xwz2u51UE7LW5wLNy53+gDXgWJA5AL3azWfO7QKmaWqlKM1rLJ2aZdRfKTGmkcto1EdK+jlNoek6Rq8/IV/nRfYrtIPCdKC8TPho9fP+VKBIM=
  - secure: bMwWaivAaYZDbThWN0p5eEjzW24jKKW1KUItT6TU4c6tAuJoDLFQ6jlI5+1Nsr7ykYbif+QruL9+xdjXUoP9lYZ0Kd54wnbaYaFtM6BQzdCxF7pvIZ3ivXdCkOOfX6+gkijCcBNNk9mpdvGZgb6iEjuAr+RbSztKJA2M8tete+KL30XH4jHdROXOwX6hOIYqjhIKlBn4TRu0LPqYvDNzVCSkJFaBbq715Ge7GXJmndbj0+xHKa+Zw361PnWnySZmTMK3bOW1Q6uEqQt45PBb++GwplRRLvPb33F/lbKUYSiZtyPrCJyiWMQwTQLy6Lq6m0E4gGmgbRiQBS+7s0++Jpy8oPvL1uO3GSvqiGc2ujeUu80PaimNqK968ud9XZIhPXCTqZqlihq3acSQGm0ECFv3v5Y73AOC1gosBh+GBD0iDFS1pVR2JYA/5aHEt/iUxXlp2dBdVbrrhGk0yLwICLNowVfZNzaj7Y9v7xiNb6JPy7J67oFD5GPWGhSIVWQAGISt6MqBrtK1YW1m2aUAkgoZPXckgLI69H6Ih7kFDgAUV4E0dwe9idWjecQsDLJaQYWWd5+G9tyrR8/tjKNSZEeu1i9sq8JMkg/K4nrkt//j04lqGGUwQusgeKhKAqCDPw+NibU2AdBdCuvzrhgIA3bHl03S4Qc5QDMqOkrmelI=
  - secure: uD0gVrkSPiIvisqVwT9WlrABSeJG+965R7u4jFohcVXSoEM9wT8Ib0j+JGO21aLQRNyh9C/57FGKgXpuK9WoWc0lUOEHepE/LLyTrn0PxprRo0/xr0DTLEo27fGm/dMKTMBtvwl0JqMsuHGZcKg8VODnGKzmfuxO2arVuAHc+pay7esd2x3f4XzWg/+Ah4uA5613OTXElmyjwPryPaT+aGVsGODWU3L0pG+dZUzQo00Tof/OSvsaNaePJusCPU3RapvMkyJcdip0kj6FknB2cVTeRZTtPLAuy1IbnqzsMvPjlDC8CNNL6L18A0eUOu5DNtxx1NhxfxROuHPTchq0tgr0ZT6XEpW72uc0RQzBErfI33Pblqo+ClmNT1UIOsvM8b7Q+bDUdpDN9l/cCEW2L2FvErUrEQpjSjef8odnVZW0TO/rub9GQ5CcFepgb5X3krCa+Mt1wQkTJHQlOkYiha54clCqSTKtCK38hwKXlGHPmTHZFUR09VIdw5s2FpvD8ZbG0hAluMCB0rXvdBUOmjtJgK1kYq2uG17PMs2oORXduutyJbuZNb+w02/vE75rNc/Tr+T3Qa2jIM/FQLWqwcamFVKP2NO3KaH95zP+tM+ZCZZdmxflIrv07u7MGWRelNx7ByfEEkB6hqs4clPtTcfe/WmPWmYJeCeKldmJjs8=
  
deploy:
  provider: heroku
  api_key:
    secure: pfRvxVvTD148Msj3VGxRW+JNs7dyAqooRbInH+r/anjcISDU/TyW6oeWKzDVDGRbawGOdkAFxNYDrQctazDdkt3u9cNlvwuYcl+5e2EVv8spmF9uBYOiV0FROM7OsDMsJlLgnDXX+WIoJptj6cpWjLvmJ3ZXKSKlr0yrN7FVFPwW2PPF1FEV5CWQvfAXu+IgZUgF9BJ1Mpi78JVRk1s4MqS7i8RQcmUE7XQ9rHdGIt2VUkcfbYWXvR2mO/BoGHdPZzqzAFsQvn4YUQ0hTlM9uCCbaPTPChTokqU0G7Hp1NmdYG1IyreU3DjvfG45D4PLsJ4I9ducptxJsx7alGFGgY4roRKQWW0UvuP8Az/0QQWrcbQMXZi5DRbg3JY3a0oawwWevMbzJ2wD75S4JVydgXrDh1QYLnO5hZb35iCyzqBw35ShU9uXCEwtBJEYVLViZfKH/dO5epsdkwFbMV1iL+DMwPFmWOqmRovHKkTzizyEaVeeaFkOm2o4iakeqYLkJLszrleE/nSx62tLAjTy78B1fDuZdPxCG/h/3RI8IB9+QuBtz1jxDGpZBVOuzXH7P85JNplpDCNCGh6HSzR7Z+L7fzDknD4teLpvRgXA4VCnw7WT4dLCftq5uNUmc08estww9a831H0P9mwmBZ+Ebtgg1G9Wvnlzgx+mZ0ChDO8=
  app: grammable-joel-pankito
  on:
    repo: joelpankito/grammable-
  run:
      - "rake db:migrate"
      - restart