addons:
  postgresql: 9.6
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
language: ruby
rvm:
- 2.5.3
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
env:
  AWS_ACCESS_KEY: 
    secure: "TZ04l/GfjuLCh8xhIONuNLCwJMsV20SDjAFIhhaHukCA2ivUouEd8xueBSaHuSDBTDxS8nzBRRrSgoBnyKVzShOMX4kDVKq6cvMyBliLSZ0C8uMW90WwRxND9UUB+nOmTV9sk8HXPJwHSKkfiRYgsiTIdxdo1R7ZHliv2Vczhm1vKPYb9Zsw1jF0ZP4cKcx2BEPJXbVXPo1FZNwNYiEVJiQoYgPpFW8DUDWfc2oRQifclSpuYRhektDAgRxYCiC0IVpIjwpbmadjOi/Ohi8Ri3VjvSbMRrPd0AubmehyEPKml46L5CEt0mFt82SUa961Z8n8h2bKG82rn+0nUyEHBtYBCyqDR2sggP6Hcbtrm3QwWqiJk1wqdc5tvVwp4uN5JICWzzUoyEwjPf3ZgGWWFT4H2Dfo+IiBSVyFzBV68oxAU4MGfEbydeXIgOs0GgnuZJ5oV3wRmrlGjzsvikRaY76wEcBOQpoynUuCEXVxv+/SBCpTMOLwGKpMai5w4F+1Fndqy14mWOdToxxi7L5tGWLbsiTZcaHyNG5tkWiY0xZsWGnts26juJTH7s7RrFK9kDhmSi90fLM6sJxzjX6w5Icr31ArT8ufX7EPgn4EwCUssKM78nq1GD++A0P+0+l/0fEpjIx1xIgPp07tV3xwI3JhwIZQKzvQc2HrApM7GUQ="
  AWS_SECRET_KEY: 
    secure: "SmvAzimY8fcxXUfcGOHCm36R2Tk4/GwtVW4Ra8HtAF+GTPcWVEkUlIQzE6RK/We0U4G5tqrNujFhUDkYJHylcEhAExLozfex0nDoIN7uEmtrTMM5CSnTYLbc5RL47cBhAIcBLOagx2c08VTDpn6HGWTWiJ5pjUx4S6O0kih4D2hVJ0xa8FuweGbF7yVh6y16ZIEhWogbddx2g5Agz8SKsCDUIASf0RZpFqjm4TeTDaco+qqFzO3tBLZtPjqQukZqsZ0Kt4iy5R4rDyV4mh1o+WdBSGEqVtUc6vc51qV/RAamAIZg3UKjhIG/7ncE2UR6442RwX9Y3effYQ5xOSPBqT8w4thy+KvEdlvOU0qG6OGRkycJNlDWtj2J3OTyS3VEWhZx5HgjYTOHSArBUz7y1E8idaDX4svm8Id1xuawMCtzk1c+vZDKKbtziq/avo5UQtKi+iZUJQAsHHrXX0p7ERCEHEOh99BmKkQwAh/w2jZoHTT87xyVedM5E8uWOwWfJwe0AiJxWHLCf9xyDJ9s5rDMz65fuB/b5StghZI3hJsiioZqKfSCgR4csMuQY2cUunjdZBKKVUXTFLRB74gqGyWiOFlFRh1l9+0UH8r91On1aiXZyW77aLjDXzXS/8Z9BdfonRNFR+vDehD3DjeCb1iEdZ0Rd8IN9E86PJ8h4GI="
  AWS_BUCKET: "grams-joel-pankito"